### ISSUE TITLE
Please update Patates version

### ISSUE THREAD

**Issue by tismayil** [burakbesli/nodequery-api#1]
.

**Comment by burakbesli** [comment]
Coming soon Patates version :)

**Comment by tismayil** [comment]
With patates v3.5 (Soğan relase)

**Comment by tismayil** [comment]
@whitehat61  wtf? man $this->pilavustu('title : ' , array(100 => "qram et doner")); 
not working

**Comment by tismayil** [comment]
@burakbesli this version is Haslam or MercimekCorba ?

**Comment by tismayil** [comment]
<?php
use Mirza\SictiBezine;
?>
This line error pleasee help.

**Comment by whitehat61** [comment]
@tismayil u can fix that issues on this syntax $this->ahmetusta()->pilavustu('title : ' , array(100 => "qram et doner"));

Enjoy :)

**Comment by burakbesli** [comment]
@tismayil Mirza forever please fixed
use Mirza\HepSicarBeze;

**Comment by tismayil** [comment]
@burakbesli @whitehat61

**Comment by tismayil** [comment]
hello how are you ?

**Comment by tismayil** [comment]
whatsapp man ?

**Comment by tismayil** [comment]
Zista tiriska

**Comment by burakbesli** [comment]
Prişka

**Comment by tismayil** [comment]
fedo niska manu de sabida ?

**Comment by burakbesli** [comment]
ZALATOYA 👍

**Comment by tismayil** [comment]
@whitehat61 is fake patates
